# Generated by Django 5.1.11 on 2025-11-05 16:48

import emerg_database.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("plan", models.CharField(default="lite", max_length=20)),
                ("fiscal_data", models.JSONField(blank=True, default=dict)),
                ("business_data", models.JSONField(blank=True, default=dict)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", emerg_database.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Tax ID"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "is_supplier",
                    models.BooleanField(default=False, verbose_name="Is Supplier"),
                ),
                (
                    "is_client",
                    models.BooleanField(default=False, verbose_name="Is Client"),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Favorite"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="FiscalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Año")),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuración"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Fiscal",
                "verbose_name_plural": "Configuraciones Fiscales",
            },
        ),
        migrations.CreateModel(
            name="FiscalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("business_type", models.CharField(blank=True, max_length=50)),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("contact_full_name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=emerg_database.models.logo_upload_to,
                    ),
                ),
                ("vat_registered", models.BooleanField(default=False)),
                ("vat_number", models.CharField(blank=True, max_length=32)),
                ("pps_number", models.CharField(blank=True, max_length=16)),
                ("tax_country", models.CharField(default="IE", max_length=2)),
                ("tax_region", models.CharField(blank=True, max_length=50)),
                ("addr_line1", models.CharField(blank=True, max_length=200)),
                ("addr_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("eircode", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="IE", max_length=2)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("payment_terms", models.CharField(blank=True, max_length=100)),
                ("invoice_defaults", models.BooleanField(default=True)),
                ("late_notice", models.TextField(blank=True)),
                ("payment_methods", models.TextField(blank=True)),
                (
                    "accounting_method",
                    models.CharField(default="invoice", max_length=16),
                ),
                ("vat_schemes", models.JSONField(blank=True, default=dict)),
                ("period_type", models.CharField(default="monthly", max_length=10)),
                ("fiscal_year_start", models.DateField(blank=True, null=True)),
                ("reminders_enabled", models.BooleanField(default=True)),
                ("reminder_days_before_due", models.PositiveIntegerField(default=7)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("bic", models.CharField(blank=True, max_length=11)),
                ("invoice_footer", models.TextField(blank=True)),
                ("auto_detect_contacts", models.BooleanField(default=True)),
                (
                    "ocr_confidence_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.70"), max_digits=4
                    ),
                ),
                ("tax_bands", models.JSONField(blank=True, default=dict)),
                ("invoice_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Profile",
                "verbose_name_plural": "Fiscal Profiles",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("purchase", "Purchase"),
                            ("credit_note", "Credit Note"),
                        ],
                        default="purchase",
                        max_length=12,
                        verbose_name="Invoice Type",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=64, verbose_name="Invoice Number"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Project"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="VAT Amount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Confirmed"),
                ),
                (
                    "due_policy",
                    models.CharField(
                        choices=[
                            ("DUE_ON_RECEIPT", "Due on receipt"),
                            ("NET_7", "Net 7 days"),
                            ("NET_15", "Net 15 days"),
                            ("NET_30", "Net 30 days"),
                            ("NET_60", "Net 60 days"),
                            ("EOM", "End of month"),
                            ("CUSTOM_DAYS", "Custom days"),
                            ("CUSTOM_DATE", "Specific date"),
                        ],
                        default="NET_30",
                        max_length=20,
                        verbose_name="Due Policy",
                    ),
                ),
                (
                    "due_days",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Days Until Due"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Summary"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_credit_note",
                    models.BooleanField(default=False, verbose_name="Is Credit Note"),
                ),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=emerg_database.models.invoice_upload_to,
                        verbose_name="Original File",
                    ),
                ),
                (
                    "credit_note_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Credit Note Reason"
                    ),
                ),
                (
                    "ocr_data",
                    models.JSONField(blank=True, default=dict, verbose_name="OCR Data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="emerg_database.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.CreateModel(
            name="InvoiceConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Descripción del Concepto"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("21.00"),
                        max_digits=5,
                        verbose_name="% IVA",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Importe",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="emerg_database.invoice",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto de Factura",
                "verbose_name_plural": "Conceptos de Factura",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Proyecto"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("completed", "Completado"),
                            ("on_hold", "En Pausa"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Presupuesto",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
            },
        ),
        migrations.CreateModel(
            name="TaxPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("yearly", "Anual"),
                        ],
                        default="monthly",
                        max_length=10,
                        verbose_name="Tipo de Período",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha Fin")),
                (
                    "status",
                    models.CharField(
                        default="draft", max_length=20, verbose_name="Estado"
                    ),
                ),
                (
                    "tax_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos Fiscales"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período Fiscal",
                "verbose_name_plural": "Períodos Fiscales",
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "name"], name="emerg_datab_user_id_99baef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("user", "tax_id")},
        ),
        migrations.AlterUniqueTogether(
            name="fiscalconfig",
            unique_together={("user", "year")},
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "date"], name="emerg_datab_user_id_50ed51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "status"], name="emerg_datab_user_id_f51505_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "invoice_type"], name="emerg_datab_user_id_aaa12f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "is_credit_note"], name="emerg_datab_user_id_4dbad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "due_date"], name="emerg_datab_user_id_e916da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("user", "invoice_number")},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "status"], name="emerg_datab_user_id_cddf04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "start_date"], name="emerg_datab_user_id_6a21fc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="taxperiod",
            index=models.Index(
                fields=["user", "start_date", "end_date"],
                name="emerg_datab_user_id_bdf3c9_idx",
            ),
        ),
    ]
