# Generated by Django 5.1.11 on 2025-11-12 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emerg_database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="contact",
            name="cellphone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Cellphone"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_address",
            field=models.TextField(blank=True, verbose_name="Client Address"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_cellphone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Client Cellphone"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Client Email"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Client Name"
            ),
        ),
        migrations.AddField(
            model_name="invoiceconcept",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Importe de Descuento",
            ),
        ),
        migrations.AddField(
            model_name="invoiceconcept",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="% Descuento",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["user", "email"], name="emerg_datab_user_id_bc4161_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "client_name"], name="emerg_datab_user_id_be80b0_idx"
            ),
        ),
    ]
